wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1640092422
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      - 16
      4: 3.9.5
      5: 0.12.9
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 512
block_size:
  desc: null
  value: null
data:
  desc: null
  value:
  - ../data/AA66266AA.npy
  - ../data/AA662266AA.npy
learning_rate:
  desc: null
  value: 0.005
loss:
  desc: null
  value: NLLLoss
lstm_hidden_dim:
  desc: null
  value: 64
lstm_input_dim:
  desc: null
  value: 19
lstm_num_layers:
  desc: null
  value: 1
model_name:
  desc: null
  value: ' LeakyReluLSTM'
num_blocks:
  desc: null
  value: 6
num_classes:
  desc: null
  value: 2
num_epochs:
  desc: null
  value: 150
num_features:
  desc: null
  value: 19
optimizer:
  desc: null
  value: Adam
test_size:
  desc: null
  value: 7925
train_size:
  desc: null
  value: 31704
weight_decay:
  desc: null
  value: 0.001
